# Generated by Django 5.2.8 on 2025-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
    ]
