# Generated by Django 5.2.8 on 2025-12-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1', models.CharField(max_length=100)),
                ('service2', models.CharField(max_length=100)),
                ('service3', models.CharField(max_length=100)),
                ('service4', models.CharField(max_length=100)),
                ('service5', models.CharField(max_length=100)),
                ('service6', models.CharField(max_length=100)),
                ('conseilImage', models.ImageField(upload_to='images/Servicedetail/')),
                ('nomservice', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('sousTitr1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='images/Servicedetail/')),
                ('explication', models.TextField()),
                ('sousTitr2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=100)),
                ('block1', models.CharField(max_length=100)),
                ('contenu1', models.TextField()),
                ('block2', models.CharField(max_length=100)),
                ('contenu2', models.TextField()),
                ('block3', models.CharField(max_length=100)),
                ('contenu3', models.TextField()),
                ('sousTitr3', models.CharField(max_length=100)),
                ('descript1', models.CharField(max_length=400)),
                ('descript2', models.CharField(max_length=400)),
                ('ligne1', models.CharField(max_length=100)),
                ('ligne2', models.CharField(max_length=100)),
                ('ligne3', models.CharField(max_length=100)),
                ('ligne4', models.CharField(max_length=100)),
                ('ligne5', models.CharField(max_length=100)),
                ('sousligne1', models.CharField(max_length=100)),
                ('sousligne2', models.CharField(max_length=100)),
                ('sousligne3', models.CharField(max_length=100)),
                ('ligne6', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'servicedetail',
            },
        ),
    ]
