# Generated by Django 5.2.8 on 2025-12-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_servicedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/Blog/')),
                ('blog1', models.CharField(max_length=100)),
                ('titre1', models.CharField(max_length=100)),
                ('contenu1', models.TextField()),
                ('auteur1', models.CharField(max_length=100)),
                ('date1', models.DateField(auto_now_add=True)),
                ('nombre_commentaire1', models.IntegerField()),
                ('nombre_vue1', models.CharField(max_length=100)),
                ('image2', models.ImageField(upload_to='images/Blog/')),
                ('blog2', models.CharField(max_length=100)),
                ('titre2', models.CharField(max_length=100)),
                ('contenu2', models.TextField()),
                ('auteur2', models.CharField(max_length=100)),
                ('date2', models.DateField(auto_now_add=True)),
                ('nombre_commentaire2', models.IntegerField()),
                ('nombre_vue2', models.CharField(max_length=100)),
                ('image3', models.ImageField(upload_to='images/Blog/')),
                ('blog3', models.CharField(max_length=100)),
                ('titre3', models.CharField(max_length=100)),
                ('contenu3', models.TextField()),
                ('auteur3', models.CharField(max_length=100)),
                ('date3', models.DateField(auto_now_add=True)),
                ('nombre_commentaire3', models.IntegerField()),
                ('nombre_vue3', models.CharField(max_length=100)),
                ('image4', models.ImageField(upload_to='images/Blog/')),
                ('blog4', models.CharField(max_length=100)),
                ('titre4', models.CharField(max_length=100)),
                ('contenu4', models.TextField()),
                ('auteur4', models.CharField(max_length=100)),
                ('nombre_commentaire4', models.IntegerField()),
                ('nombre_vue4', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='bouton',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='join',
            table='join',
        ),
    ]
