# Generated by Django 5.2.8 on 2025-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_blog_alter_slider_bouton_alter_join_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=800),
        ),
    ]
