# Generated by Django 5.2.8 on 2025-12-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='lien',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
