# Generated by Django 5.2.8 on 2025-12-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_video_video_video_lien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='lien',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to='Video/video/'),
        ),
    ]
